# This file describes the alternative machine learning models
# available to the dream script.
#
# To add a new model, follow the examples below. Each
# model requires a model config file, a weights file,
# and the width and height of the images it
# was trained on.
stable-diffusion-1.4:
  config: configs/stable-diffusion/v1-inference.yaml
  weights: models/ldm/stable-diffusion-v1/model.ckpt
  vae: models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
  description: Stable Diffusion inference model version 1.4
  default: false
  width: 512
  height: 512
stable-diffusion-1.5:
  config: configs/stable-diffusion/v1-inference.yaml
  weights: models/ldm/stable-diffusion-v1/stable-diffusion-v1-5/v1-5-pruned-emaonly.ckpt
  vae: models/ldm/stable-diffusion-v1/vae-ft-mse-840000-ema-pruned.ckpt
  description: Stable Diffusion inference model version 1.5
  width: 512
  height: 512
  default: true
waifu-diffusion-1.3:
  config: configs/stable-diffusion/v1-inference.yaml
  weights: models/ldm/stable-diffusion-v1/wd-v1-3-float16.ckpt
  description: 1.3 Waifu Diffusion model trained on 600,000 high-resolution Danbooru images for 10 Epochs.
  width: 512
  height: 512
  default: false
zeipher-F111-Female-Nude:
  config: configs/stable-diffusion/v1-inference.yaml
  weights: models/ldm/stable-diffusion-v1/f111.ckpt
  description: from https://ai.zeipher.com/
  width: 512
  height: 512
  default: false
zeipher-F222-Female-Nude:
  config: configs/stable-diffusion/v1-inference.yaml
  weights: models/ldm/stable-diffusion-v1/f222.ckpt
  description: from https://ai.zeipher.com/
  width: 512
  height: 512
  default: false